# rust-toolchain
# https://rust-lang.github.io/rustup/overrides.html

# targets and components are additive to the systems default values
[toolchain]
# rustc 1.91: nightly needed as some unstable build features are required
channel = "nightly-2025-09-07"
profile = "minimal"
targets = [
  "x86_64-unknown-uefi"
]
components = [
  "cargo",
  "clippy",
  "miri",
  # for build-std feature
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
