[package]
name = "util"
version = "0.1.0"
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bit_ops = { workspace = true }
log = { workspace = true }
